import nodemailer from "nodemailer";
import { createToken } from "./JWT.js";
import dotenv from "dotenv";
import path from "node:path";
import * as fs from "fs";
import * as handlebars from "handlebars";

dotenv.config();

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: "patoliya.nk1@gmail.com",
    pass: process.env.GOOGLE_APP_PASSWORD, // The 16-character App Password
  },
});

/**
 * send verification mail.
 * @param to email where we want to send email. 
 * @param Token verification token which is generated by JWT.
 */
export const sendMail = async (to: string, Token: string) => {
  const __dirname = path.resolve();
  const filePath = path.join("./src/utils/EmailTemplates/EmailVerify.html");
  const source = fs.readFileSync(filePath, "utf-8").toString();
  const template = handlebars.compile(source);
  const replacements = {
    action_url: `http://localhost:${process.env.PORT}/api/email/verify?token=${Token}`,
  };
  const htmlToSend = template(replacements);
  await transporter.sendMail({
    from: '"Post-app" <post@test.com>',
    to: to,
    subject: "Verification mail.",
    text: "Hello world?", // Plain-text version of the message
    html: htmlToSend, // HTML version of the message
  });
};

/**
 * generate Token {email,userid, role} and send on given Email.
 * @param email user email.
 * @param userId user id.
 * @param role user role
 */
export const sendTokenMail = async (
  email: string,
  userId: string,
  role: string,
) => {
  // generate Token {email,userid, role}
  const token = createToken(userId, email, role, 120);
  // send Token link
  await sendMail(email, token);
};

/**
 * use for send welcome mail.
 * @param to  email where we want to send email.
 */
export const sendWelcomeMail = async (to: string) => {
  const filePath = path.join("./src/utils/EmailTemplates/WelcomeEmail.html");
  const source = fs.readFileSync(filePath, "utf-8").toString();
  const template = handlebars.compile(source);
  const replacements = {};
  const htmlToSend = template(replacements);
  await transporter.sendMail({
    from: '"Post-app" <post@test.com>',
    to: to,
    subject: "Welcome to our Post-app Platform!",
    text: "Hello world?", // Plain-text version of the message
    html: htmlToSend, // HTML version of the message
  });
};
