// User Data
export const JSONData = [
  {
    id: 6782957737,
    firstName: "Emily",
    age: 29,
    email: "emily@gmail.com",
    isActive: true,
    address: {
      city: "New York",
      state: "NY",
      country: "USA",
    },
  },
  {
    id: 3006256981,
    firstName: "Michael",
    maidenName: "",
    age: 16,
    email: "michael@gmail.com",
    isActive: true,
    address: {
      city: "Chicago",
      state: "IL",
      country: "USA",
    },
  },
  {
    id: 4729336095,
    firstName: "Sophia",
    age: 43,
    email: "sophia@gmail.com",
    isActive: false,
    address: {
      city: "San Francisco",
      state: "CA",
      country: "USA",
    },
  },
  {
    id: 4107330510,
    firstName: "James",
    age: 46,
    email: "james@gmail.com",
    isActive: true,
    address: {
      city: "Dallas",
      state: "TX",
      country: "USA",
    },
  },
  {
    id: 9573145061,
    firstName: "Emma",
    age: 11,
    email: "emma@gmail.com",
    isActive: false,
    address: {
      city: "Seattle",
      state: "WA",
      country: "USA",
    },
  },
  {
    id: 7669076967,
    firstName: "Olivia",
    age: 23,
    email: "",
    isActive: true,
    address: {
      city: "Austin",
      state: "TX",
      country: "USA",
    },
  },
  {
    id: 9459396996,
    firstName: "Emily",
    age: 29,
    email: "emily@gmail.com",
    isActive: true,
    address: {
      city: "Boston",
      state: "MA",
      country: "USA",
    },
  },
  {
    id: 3504714177,
    firstName: "Michael",
    age: 36,
    email: "michael@gmail.com",
    isActive: false,
    address: {
      city: "Denver",
      state: "CO",
      country: "USA",
    },
  },
  {
    id: 9060631538,
    firstName: "Sophia",
    age: 13,
    email: "sophia@gmail.com",
    isActive: true,
    address: {
      city: "Los Angeles",
      state: "CA",
      country: "USA",
    },
  },
  {
    id: 7846414326,
    firstName: "James",
    age: 46,
    email: "james@gmail.com",
    isActive: true,
    address: {
      city: "Phoenix",
      state: "AZ",
      country: "USA",
    },
  },
  {
    id: 9743729261,
    firstName: "Emma",
    age: 31,
    email: "emma@gmail.com",
    isActive: false,
    address: {
      city: "Portland",
      state: "OR",
      country: "USA",
    },
  },
  {
    id: 3604954402,
    firstName: "Olivia",
    age: 23,
    email: "olivia@gmail.com",
    isActive: true,
    address: {
      city: "Miami",
      state: "FL",
      country: "USA",
    },
  },
];