import "./ui/globals.css";
import { geistMono, geistSans } from "./ui/font";
import type { Metadata } from "next";
import Wrapper from './Wrapper';
import Header from "./ui/Header";
import Footer from "./ui/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen overflow-x-auto`}
      >
        <Wrapper >
          <Header />
          {children}
          <Footer />
        </Wrapper>
      </body>
    </html>
  );
}
