export const gitHubUserAPI : string = 'https://api.github.com/users/'

export const usersSearchAPI : string = 'https://api.github.com/search/users?q='



//default data


export const tempUserData = {
    login: "facebook",
    id: 69631,
    node_id: "MDEyOk9yZ2FuaXphdGlvbjY5NjMx",
    avatar_url: "https://avatars.githubusercontent.com/u/69631?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/facebook",
    html_url: "https://github.com/facebook",
    followers_url: "https://api.github.com/users/facebook/followers",
    following_url: "https://api.github.com/users/facebook/following{/other_user}",
    gists_url: "https://api.github.com/users/facebook/gists{/gist_id}",
    starred_url: "https://api.github.com/users/facebook/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/facebook/subscriptions",
    organizations_url: "https://api.github.com/users/facebook/orgs",
    repos_url: "https://api.github.com/users/facebook/repos",
    events_url: "https://api.github.com/users/facebook/events{/privacy}",
    received_events_url: "https://api.github.com/users/facebook/received_events",
    type: "Organization",
    user_view_type: "public",
    site_admin: false,
    name: "Meta",
    company: null,  
    blog: "https://opensource.fb.com",
    location: "Menlo Park, California",
    email: null,
    hireable: null,
    bio: "We are working to build community through open source technology. NB: members must have two-factor auth.",
    twitter_username: "MetaOpenSource",
    public_repos: 161,
    public_gists: 12,
    followers: 34210,
    following: 0,
    created_at: "2009-04-02T03:35:22Z",
    updated_at: "2024-12-27T21:10:02Z"
}


export const tempRepoData = {
  id: 172581071,
  node_id: "MDEwOlJlcG9zaXRvcnkxNzI1ODEwNzE=",
  name: ".github",
  full_name: "facebook/.github",
  private: false,
  owner: {
    login: "facebook",
    id: 69631,
    node_id: "MDEyOk9yZ2FuaXphdGlvbjY5NjMx",
    avatar_url: "https://avatars.githubusercontent.com/u/69631?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/facebook",
    html_url: "https://github.com/facebook",
    followers_url: "https://api.github.com/users/facebook/followers",
    following_url: "https://api.github.com/users/facebook/following{/other_user}",
    gists_url: "https://api.github.com/users/facebook/gists{/gist_id}",
    starred_url: "https://api.github.com/users/facebook/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/facebook/subscriptions",
    organizations_url: "https://api.github.com/users/facebook/orgs",
    repos_url: "https://api.github.com/users/facebook/repos",
    events_url: "https://api.github.com/users/facebook/events{/privacy}",
    received_events_url: "https://api.github.com/users/facebook/received_events",
    type: "Organization",
    user_view_type: "public",
    site_admin: false
  },
  html_url: "https://github.com/facebook/.github",
  description: "Default Community health files for Facebook projects",
  fork: false,
  url: "https://api.github.com/repos/facebook/.github",
  forks_url: "https://api.github.com/repos/facebook/.github/forks",
  keys_url: "https://api.github.com/repos/facebook/.github/keys{/key_id}",
  collaborators_url: "https://api.github.com/repos/facebook/.github/collaborators{/collaborator}",
  teams_url: "https://api.github.com/repos/facebook/.github/teams",
  hooks_url: "https://api.github.com/repos/facebook/.github/hooks",
  issue_events_url: "https://api.github.com/repos/facebook/.github/issues/events{/number}",
  events_url: "https://api.github.com/repos/facebook/.github/events",
  assignees_url: "https://api.github.com/repos/facebook/.github/assignees{/user}",
  branches_url: "https://api.github.com/repos/facebook/.github/branches{/branch}",
  tags_url: "https://api.github.com/repos/facebook/.github/tags",
  blobs_url: "https://api.github.com/repos/facebook/.github/git/blobs{/sha}",
  git_tags_url: "https://api.github.com/repos/facebook/.github/git/tags{/sha}",
  git_refs_url: "https://api.github.com/repos/facebook/.github/git/refs{/sha}",
  trees_url: "https://api.github.com/repos/facebook/.github/git/trees{/sha}",
  statuses_url: "https://api.github.com/repos/facebook/.github/statuses/{sha}",
  languages_url: "https://api.github.com/repos/facebook/.github/languages",
  stargazers_url: "https://api.github.com/repos/facebook/.github/stargazers",
  contributors_url: "https://api.github.com/repos/facebook/.github/contributors",
  subscribers_url: "https://api.github.com/repos/facebook/.github/subscribers",
  subscription_url: "https://api.github.com/repos/facebook/.github/subscription",
  commits_url: "https://api.github.com/repos/facebook/.github/commits{/sha}",
  git_commits_url: "https://api.github.com/repos/facebook/.github/git/commits{/sha}",
  comments_url: "https://api.github.com/repos/facebook/.github/comments{/number}",
  issue_comment_url: "https://api.github.com/repos/facebook/.github/issues/comments{/number}",
  contents_url: "https://api.github.com/repos/facebook/.github/contents/{+path}",
  compare_url: "https://api.github.com/repos/facebook/.github/compare/{base}...{head}",
  merges_url: "https://api.github.com/repos/facebook/.github/merges",
  archive_url: "https://api.github.com/repos/facebook/.github/{archive_format}{/ref}",
  downloads_url: "https://api.github.com/repos/facebook/.github/downloads",
  issues_url: "https://api.github.com/repos/facebook/.github/issues{/number}",
  pulls_url: "https://api.github.com/repos/facebook/.github/pulls{/number}",
  milestones_url: "https://api.github.com/repos/facebook/.github/milestones{/number}",
  notifications_url: "https://api.github.com/repos/facebook/.github/notifications{?since,all,participating}",
  labels_url: "https://api.github.com/repos/facebook/.github/labels{/name}",
  releases_url: "https://api.github.com/repos/facebook/.github/releases{/id}",
  deployments_url: "https://api.github.com/repos/facebook/.github/deployments",
  created_at: "2019-02-25T20:39:32Z",
  updated_at: "2026-01-07T22:51:14Z",
  pushed_at: "2023-11-02T06:05:19Z",
  git_url: "git://github.com/facebook/.github.git",
  ssh_url: "git@github.com:facebook/.github.git",
  clone_url: "https://github.com/facebook/.github.git",
  svn_url: "https://github.com/facebook/.github",
  homepage: null,
  size: 6,
  stargazers_count: 17,
  watchers_count: 17,
  language: null,
  has_issues: false,
  has_projects: true,
  has_downloads: true,
  has_wiki: false,
  has_pages: false,
  has_discussions: false,
  forks_count: 119,
  mirror_url: null,
  archived: true,
  disabled: false,
  open_issues_count: 0,
  license: null,
  allow_forking: true,
  is_template: false,
  web_commit_signoff_required: false,
  topics: [],
  visibility: "public",
  forks: 119,
  open_issues: 0,
  watchers: 17,
  default_branch: "main"
}

